Crash_Analysis/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path(
        "map/simple/",
        TemplateView.as_view(template_name="map_generated.html"),
    ),
    path('map/', views.index, name='map'),
    path('accidents/<int:year>/<int:st_case>/', views.accident_detail, name='accident_detail'),
    path('accidents/<int:year>/', views.accident_year_index, name='accident_year_index'),
    path('accidents/', views.accident_index, name='accident_index'),
]

FARS_Project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("api/", include("Crash_Analysis.api")),
    path("", include("Crash_Analysis.urls")),
]

Crash_Analysis/models.py
from django.contrib.gis.db import models

from .dicts import *

# Ensures that get_FOO_display always wraps the field in str()
# nvm this doesn't work
class CustomBaseModel(models.Model):
    class Meta:
        abstract = True
    def __getattr__(self, name):
        if name.startswith('get_') and name.endswith('_display'):
            field_name = name[4:-8]
            try:
                choices = self._meta.get_field(field_name).choices
                value = super().__getattr__(field_name)
                return dict(choices).get(str(value), "Unknown")
            except Exception:
                pass
        return super().__getattr__(name)


class Accident(CustomBaseModel):
    state = models.PositiveSmallIntegerField("State", choices=STATE)
    # state = models.PositiveSmallIntegerField()
    st_case = models.PositiveIntegerField("Case Number")
    peds = models.PositiveSmallIntegerField("Number of Forms Submitted for Persons Not in Motor Vehicles")
    pernotmvit = models.PositiveSmallIntegerField("Number of Persons Not in Motor Vehicles In-Transport")
    ve_total = models.PositiveSmallIntegerField("Number of Vehicle Forms Submitted - All")
    ve_forms = models.PositiveSmallIntegerField("Number of Motor Vehicles In-Transport")
    pvh_invl = models.PositiveSmallIntegerField("Number of Parked/Working Vehicles")
    persons = models.PositiveSmallIntegerField("Number of Person Forms Submitted")
    permvit = models.PositiveSmallIntegerField("Number of Persons in Motor Vehicles In-Transport")
    county = models.PositiveSmallIntegerField("County")
    city = models.PositiveSmallIntegerField("City")
    # month = models.PositiveSmallIntegerField()
    # day = models.PositiveSmallIntegerField()
    # day_week = models.PositiveSmallIntegerField()
    # year = models.PositiveSmallIntegerField()
    # hour = models.PositiveSmallIntegerField()
    # minute = models.PositiveSmallIntegerField()
    datetime = models.DateTimeField("Crash Date/Time (Local)")
    tway_id = models.CharField("Trafficway Identifier 1")
    tway_id2 = models.CharField("Trafficway Identifier 2")
    route = models.PositiveSmallIntegerField("Route Signing", choices=ROUTE)
    rur_urb = models.PositiveSmallIntegerField("Land Use", choices=RUR_URB)
    func_sys = models.PositiveSmallIntegerField("Functional System", choices=FUNC_SYS)
    rd_owner = models.PositiveSmallIntegerField("Ownership", choices=RD_OWNER)
    nhs = models.PositiveSmallIntegerField("National Highway System", choices=NHS)
    sp_jur = models.PositiveSmallIntegerField("Special Jurisdiction", choices=SP_JUR)
    milept = models.PositiveIntegerField("Milepoint")
    # latitude = models.FloatField()
    # longitud = models.FloatField()
    location = models.PointField("Global Position")
    harm_ev = models.PositiveSmallIntegerField("First Harmful Event", choices=HARM_EV[0][1]) # todo: change to reflect datetime.year
    man_coll = models.PositiveSmallIntegerField("Manner of Collision of the First Harmful Event", choices=MAN_COLL[0][1]) # todo: change to reflect datetime.year
    reljct1 = models.PositiveSmallIntegerField("Relation to Junction - Within Interchange Area", choices=RELJCT1[0][1]) # todo: change to reflect datetime.year
    reljct2 = models.PositiveSmallIntegerField("Relation to Junction - Specific Location", choices=RELJCT2[0][1]) # todo: change to reflect datetime.year
    typ_int = models.PositiveSmallIntegerField("Type of Intersection", choices=TYP_INT[0][1]) # todo: change to reflect datetime.year
    rel_road = models.PositiveSmallIntegerField("Relation to Trafficway", choices=REL_ROAD[0][1]) # todo: change to reflect datetime.year
    wrk_zone = models.PositiveSmallIntegerField("Work Zone", choices=WRK_ZONE[0][1]) # todo: change to reflect datetime.year
    lgt_cond = models.PositiveSmallIntegerField("Light Condition", choices=LGT_COND[0][1]) # todo: change to reflect datetime.year
    weather = models.PositiveSmallIntegerField("Atmospheric Conditions", choices=WEATHER[0][1]) # todo: change to reflect datetime.year
    sch_bus = models.PositiveSmallIntegerField("School Bus Related", choices=SCH_BUS)
    rail = models.CharField("Rail Grade Crossing Identifier")
    not_hour = models.PositiveSmallIntegerField("Hour of Notification")
    not_min = models.PositiveSmallIntegerField("Minute of Notification")
    not_time = models.TimeField("Notification Time EMS", null = True, blank = True)
    arr_hour = models.PositiveSmallIntegerField("Hour of Arrival at Scene")
    arr_min = models.PositiveSmallIntegerField("Minute of Arrival at Scene")
    arr_time = models.TimeField("Arrival Time EMS", null = True, blank = True)
    hosp_hr = models.PositiveSmallIntegerField("Hour of EMS Arrival at Hospital")
    hosp_mn = models.PositiveSmallIntegerField("Minute of EMS Arrival at Hospital")
    hosp_time = models.TimeField("EMS Time at Hospital", null = True, blank = True)
    fatals = models.PositiveSmallIntegerField("Fatalities")
    def get_absolute_url(self):
        return "/accidents/%i/%i/" % (self.datetime.year, self.st_case)

class Vehicle(CustomBaseModel):
    st_case = models.ForeignKey(
        Accident,
        verbose_name = "Case Number",
        on_delete = models.CASCADE
    )
    veh_no = models.PositiveSmallIntegerField("Vehicle Number")
    numoccs = models.PositiveSmallIntegerField("Number of Occupants") # 99 = unknown
    unittype = models.PositiveSmallIntegerField("Unit Type", choices=UNITTYPE)
    hit_run = models.PositiveSmallIntegerField("Hit-and-Run", choices=HIT_RUN)
    reg_stat = models.PositiveSmallIntegerField("Registration State", choices=REG_STAT)
    owner = models.PositiveSmallIntegerField("Registered Vehicle Owner", choices=OWNER)
    make = models.PositiveSmallIntegerField("NSCA Make", choices=MAKE)
    model = models.PositiveSmallIntegerField("NSCA Model") # todo
    # mak_mod = models.PositiveIntegerField()
    body_typ = models.PositiveSmallIntegerField("NSCA Body Type", choices=BODY_TYP[0][1])
    mod_year = models.PositiveSmallIntegerField("Vehicle Model Year")
    vin = models.CharField("Vehicle Identification Number")
    tow_veh = models.PositiveSmallIntegerField("Vehicle Trailing", choices=TOW_VEH[0][1])
    j_knife = models.PositiveSmallIntegerField("Jackknife", choices=J_KNIFE)
    # mcarr_i1 = models.PositiveSmallIntegerField()
    # mcarr_i2 = models.PositiveIntegerField()
    mcarr_id = models.CharField("Motor Carrier Identification Number")
    v_config = models.PositiveSmallIntegerField("Vehicle Configuration", choices=V_CONFIG)
    cargo_bt = models.PositiveSmallIntegerField("Cargo Body Type", choices=CARGO_BT)
    haz_inv = models.PositiveSmallIntegerField("Hazardous Material Involvement", choices=HAZ_INV)
    haz_plac = models.PositiveSmallIntegerField("Hazardous Material Placard", choices=HAZ_PLAC)
    haz_id = models.PositiveSmallIntegerField()
    haz_cno = models.PositiveSmallIntegerField()
    haz_rel = models.PositiveSmallIntegerField()
    bus_use = models.PositiveSmallIntegerField()
    spec_use = models.PositiveSmallIntegerField()
    emer_use = models.PositiveSmallIntegerField()
    trav_sp = models.PositiveSmallIntegerField()
    underoverride = models.PositiveSmallIntegerField()
    rollover = models.PositiveSmallIntegerField()
    rolinloc = models.PositiveSmallIntegerField()
    impact1 = models.PositiveSmallIntegerField()
    deformed = models.PositiveSmallIntegerField()
    towed = models.PositiveSmallIntegerField()
    m_harm = models.PositiveSmallIntegerField()
    fire_exp = models.PositiveSmallIntegerField()
    dr_pres = models.PositiveSmallIntegerField()
    l_state = models.PositiveSmallIntegerField()
    dr_zip = models.PositiveIntegerField()
    l_status = models.PositiveSmallIntegerField()
    l_type = models.PositiveSmallIntegerField()
    cdl_stat = models.PositiveSmallIntegerField()
    l_endors = models.PositiveSmallIntegerField()
    l_compl = models.PositiveSmallIntegerField()
    l_restri = models.PositiveSmallIntegerField()
    dr_hgt = models.PositiveSmallIntegerField()
    dr_wgt = models.PositiveSmallIntegerField()
    prev_acc = models.PositiveSmallIntegerField()
    prev_sus1 = models.PositiveSmallIntegerField()
    prev_sus2 = models.PositiveSmallIntegerField()
    prev_sus3 = models.PositiveSmallIntegerField()
    prev_dwi = models.PositiveSmallIntegerField()
    prev_spd = models.PositiveSmallIntegerField()
    prev_oth = models.PositiveSmallIntegerField()
    first_mo = models.PositiveSmallIntegerField()
    first_yr = models.PositiveSmallIntegerField()
    last_mo = models.PositiveSmallIntegerField()
    last_yr = models.PositiveSmallIntegerField()
    speedrel = models.PositiveSmallIntegerField()
    vtrafway = models.PositiveSmallIntegerField()
    vnum_lan = models.PositiveSmallIntegerField()
    vspd_lim = models.PositiveSmallIntegerField()
    valign = models.PositiveSmallIntegerField()
    vprofile = models.PositiveSmallIntegerField()
    vpavetyp = models.PositiveSmallIntegerField()
    vsurcond = models.PositiveSmallIntegerField()
    vtrafcon = models.PositiveSmallIntegerField()
    vtcont_f = models.PositiveSmallIntegerField()
    p_crash1 = models.PositiveSmallIntegerField()
    p_crash2 = models.PositiveSmallIntegerField()
    p_crash3 = models.PositiveSmallIntegerField()
    pcrash4 = models.PositiveSmallIntegerField()
    pcrash5 = models.PositiveSmallIntegerField()
    acc_type = models.PositiveSmallIntegerField()
    trlr1vin = models.CharField()
    trlr2vin = models.CharField()
    trlr3vin = models.CharField()
    deaths = models.PositiveSmallIntegerField()
    dr_drink = models.PositiveSmallIntegerField()
    vpicmake = models.PositiveIntegerField("vPIC Model")
    vpicmodel = models.PositiveIntegerField("vPIC Make")
    vpicbodyclass = models.PositiveSmallIntegerField("vPIC Body Class", choices=VPICBODYCLASS)
    icfinalbody = models.PositiveSmallIntegerField("Final Stage Body Class", choices=ICFINALBODY)

Crash_Analysis/templates/accident_detail.html
{% extends 'base.html' %}
{% block content %}
<title>Accident Detail</title>
<div class="container">
    <div class="row">
        <!-- Left column for accident details -->
        <div class="col-md-6">
            <h1>Accident Details</h1>
            <p><strong>Case Number:</strong> {{ accident.st_case }}</p>
            <p><strong>Date/Time:</strong> {{ accident.datetime }}</p>
            <p><strong>Fatalities:</strong> {{ accident.fatals }}</p>
            <p><strong>Total Vehicles:</strong> {{ accident.ve_total }}</p>
            <p><strong>Total Persons:</strong> {{ accident.persons }}</p>
            <p><strong>Admin ID:</strong> {{ accident.id }}</p>

            <h1>Vehicle Details</h1>
            {% if vehicles %}
                <ul>
                {% for vehicle in vehicles %}
                    <li>Make: {{ vehicle.get_make_display }}, Model: {{ vehicle.model }}, Year: {{ vehicle.mod_year }}, Admin ID: {{ vehicle.id }}</li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No vehicles available</p>
            {% endif %}

            <h1>Person Details</h1>
            {% if persons %}
                <ul>
                {% for person in persons %}
                    <li>Age: {{ person.age }}, Sex and/or Gender: {{ person.get_sex_display }}, Person Type: {{ person.get_per_typ_display }}, Injury Severity: {{ person.get_inj_sev_display }}, Admin ID: {{ person.id }}</li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No personal information available</p>
            {% endif %}
        </div>

        <!-- Right column for the map -->
        <div class="col-md-6">
            <div class="map-container">
                <br>
                {{ map1|safe }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

Crash_Analysis/templates/accident_index.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block content %}

<style>
h1 {text-align: center;}
h2 {text-align: center;}
</style>

<title> Accidents per Year </title>

<body>
	{% render_table table %}
</body>

{% endblock %}

Crash_Analysis/templates/accident_year_index.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block content %}

<style>
h1 {text-align: center;}
h2 {text-align: center;}
</style>

<title> List of Accidents </title>
<h1> Total Number of Fatalities in {{ year }}: {{ fatals }} </h1>
<h2> Total Number of Fatal Car Accidents in {{ year }}: {{ length }} </h2>
<h2> Total Number of Persons Involved in Fatal Car Accidents in {{ year }}: {{ persons }} </h2>
<h2> Total Number of Vehicles Involved in Fatal Car Accidents in {{ year }}: {{ vehicles }} </h2>

<body>
    {% render_table aggregate_state_table %}
    {% render_table aggregate_harm_ev_table %}
    {% render_table aggregate_make_table %}
    {% render_table aggregate_body_typ_table %}
	{% render_table table %}
</body>

{% endblock %}

Crash_Analysis/templates/base.html
<!-- Taken from https://github.com/KenBroTech/HeatMap-Visualization-with-Folium-and-Django -->
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.Default.css" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.5.3/dist/leaflet.markercluster.js"></script>
    {% block extra_head %}{% endblock %}
    <!--<title>{% block title %} {% endblock %}</title>-->
</head>

<body>
    {% include 'nav.html' %}

    {% block content %}

    {% endblock %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</body>

</html>

Crash_Analysis/templates/index.html
{% extends 'base.html' %}
{% block content %}
<title>Crash Analysis Map</title>
<div class="container">
    <div class="row mt-4">
        <div class="col-md-10 offset-md-1">
            {{ map1|safe }}
        </div>
    </div>
</div>
{% endblock %}

Crash_Analysis/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-info bg-info">
    <div class="container">
        <a class="navbar-brand text-white" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link text-white" href="{% url 'accident_index' %}">Accidents <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text-white" href="{% url 'map' %}">Map <span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>